# Generated by Django 3.2.3 on 2022-03-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('region', models.TextField(verbose_name='Регион')),
                ('number', models.CharField(max_length=13, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', models.TextField(blank=True, null=True, verbose_name='Адреса')),
                ('phone_numbers', models.TextField(blank=True, null=True, verbose_name='Номера телефонов')),
                ('locations', models.TextField(blank=True, null=True, verbose_name='Ссылки локаций')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_check', models.FloatField(verbose_name='Итоговая сумма чека')),
                ('complete', models.BooleanField(default=False, verbose_name='Завершенность заказа')),
                ('order_items', models.TextField(verbose_name='Заказанные продукты')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.client', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=870, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('brand', models.ManyToManyField(to='bot_admin.Brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.category', verbose_name='Категория')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_admin.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product_price', models.FloatField(verbose_name='Цена')),
                ('total_sum', models.FloatField(verbose_name='К оплате за товар')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.client', verbose_name='Клиент')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.order', verbose_name='Id заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт в корзине',
                'verbose_name_plural': 'Продукты в корзине',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='brand',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_admin.subcategory', verbose_name='Подкатегория'),
        ),
    ]
